server:
  port: 8989

elasticsearch:
  host: localhost
  port: 9200
  connTimeout: 3000
  socketTimeout: 5000
  connectionRequestTimeout: 500
#  索引名称
  index-name: contentik
  cours-name: courseik
  username: elastic
  password: 123456

    #url: jdbc:mysql://bj-cdb-6rbxhysu.sql.tencentcdb.com:61306/xmy?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    #username: root
  #password: IaY5tp#c$Zqm%7w6uAB*Db%*2eh3NyAT
spring:
  datasource:
    url: jdbc:mysql://152.136.181.164:3306/xmy?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: xmy
    password: Xmy@1234
  elasticsearch:
    rest:
      username: elastic
      password: 123456
      uris: http://localhost:9200

mybatis-plus:
  type-aliases-package: com.pgy.esdemo.entity
  mapper-locations: classpath*:mapper/**.xml
  global-config:
    db-config:
      logic-delete-field: use_flag
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1  # 逻辑未删除值(默认为 0)
# 日志配置
logging:
  level:
    com.pgy.esdemo: debug
