server:
  port: 8989

elasticsearch:
  host: 172.21.0.16
  port: 9200
  connTimeout: 3000
  socketTimeout: 5000
  connectionRequestTimeout: 500
  index-name: contentik
  username: elastic
  password: pgy12345#

spring:
  datasource:
    url: jdbc:mysql://bj-cdb-6rbxhysu.sql.tencentcdb.com:61306/xmy?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: IaY5tp#c$Zqm%7w6uAB*Db%*2eh3NyAT
  elasticsearch:
    rest:
      username: elastic
      password: pgy12345#
      uris: http://172.21.0.16:9200

mybatis-plus:
  type-aliases-package: com.pgy.esdemo.entity
  mapper-locations: classpath*:mapper/**.xml
  global-config:
    db-config:
      logic-delete-field: use_flag
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1  # 逻辑未删除值(默认为 0)
# 日志配置
logging:
  level:
    com.pgy.esdemo: debug
